sudo: false

dist: trusty
language: erlang
otp_release:
  - 23.0
  - 22.3
  - 22.2
  - 22.1
  - 22.0
  - 21.3
  - 21.2
  - 21.1
  - 21.0
  - 20.2
  - 20.1
  - 20.0
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2.1
  - 18.2
  - 18.1
  - 18.0

env:
  global:
      - secure: "Jk1W4GtZ8rIg0fBsPepNMwipt1m6wkgYGJbuDiGUAXp8o0HD92aBCO95z4YvcYM9TxnAgpgxtUrlDXrZe5WhyAapJTW7HVm3JcsMpAfJAnGDrDeDrkI+A5V/I+ynFZ1F6F/2dKNQWJV3ieuwRojjH/dc3AVqYMWND0oAD/YWwkg="

addons:
  apt:
    packages:
      - autotools-dev
      - libpam0g-dev
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-font-utils
      - texlive-extra-utils
      - ghostscript
      - cadaver

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

env:
  - PATH=$PATH:.

install:
  - autoreconf -vfi

before_script:
  - ./configure

script:
  - make check -j4 V=1

after_script:
  - ./scripts/upload-travis-build-artifacts
  - make clean
  - rebar3 compile
